image: node:20.10.0 

stages:
  - prepare
  - test
  - build
  - publish


install:
  stage: prepare
  tags:
    - docker
  retry: 1
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 24h
    when: on_success
    paths:
      - node_modules/
  script:
    - npm install --no-audit --no-fund --verbose
  rules:
    - if: $CI_COMMIT_BRANCH       # If changes are pushed to any branch.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG          # Run this job when a tag is created


test:
  stage: test
  tags:
    - docker
  dependencies:
    - install
  script:
    - npm test
  rules:
    - if: $CI_COMMIT_BRANCH       # If changes are pushed to any branch.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG          # Run this job when a tag is created


build:
  stage: build
  tags:
    - docker
  dependencies:
    - install
  artifacts:
    expire_in: 24h
    when: on_success
    paths:
      - dist/
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_TAG          # Run this job when a tag is created


publish:
  stage: publish
  tags:
    - docker
  dependencies:
    - install
    - build
  interruptible: false
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    - npm publish --verbose
  rules:
    - if: $CI_COMMIT_TAG          # Run this job when a tag is created